### ISSUE TITLE
gentype producing wrong type for inner join

### ISSUE THREAD

**Issue by louisgv** [supabase/postgres-meta#595] opened 2023-07-19 06:12 UTC
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When creating an inner join via a `!inner(*)` query, the inferred type returns an array, but the actual data is a single object.

## To Reproduce

```ts
await supabase
      .from('deadwood')
      .select('*, cs!inner(*)')
```

## Expected behavior

deadwood.cs should be typed correctly

## System information

- OS: macOS
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: 1.77.9
- Version of Node.js: 18.x

**Comment by sweatybridge** [comment] 2023-10-24 06:05
The underlying cause seems to be non-handling of unique constraint. Closing as a duplicate of https://github.com/supabase/postgres-meta/issues/612

**Closed** 2023-10-24 06:05 UTC
Labels: bug
