### ISSUE TITLE
supabase gen types: Support for tsrange

### ISSUE THREAD

**Issue by SanjoSolutions** [supabase/postgres-meta#830] opened 2024-11-13 07:48 UTC
Right now when I run `supabase gen types --local --lang=typescript` it outputs columns of type `tsrange` as `unknown`. Please output it as `string` instead.

Tested with version 1.219.2 and 1.223.2.

**Comment by sweatybridge** [comment] 2024-11-15 06:47
Closing as duplicate of https://github.com/supabase/postgres-meta/issues/840

**Closed by sweatybridge** 2024-11-15 06:47 UTC
